"use client";

import { useState, useEffect, useMemo, createContext, useContext } from "react";
import { format } from "date-fns";
import { DateRange } from "react-day-picker";
import { motion } from "framer-motion";
import { toast } from "sonner";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import {
  PieChart,
  Pie,
  Cell,
  ResponsiveContainer,
  Tooltip as RechartsTooltip,
} from "recharts";
import {
  ComposableMap,
  Geographies,
  Geography,
  Marker,
  Line,
} from "react-simple-maps";
import {
  Shield,
  Users,
  AlertTriangle,
  CheckCircle,
  Activity,
  Download,
  LayoutDashboard,
  Settings,
  BarChart3,
  LogOut,
  Globe,
  FileText,
  Search,
  PlusCircle,
  MoreHorizontal,
  Calendar as CalendarIcon,
  Target,
  ShieldAlert,
  ScanLine,
  Flag,
  Server,
  Database,
  Cpu,
  ShieldCheck,
  UserCheck,
  UserX,
  LucideProps,
} from "lucide-react";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import { Calendar } from "@/components/ui/calendar";
import { Toaster } from "@/components/ui/sonner";
import { Slider } from "@/components/ui/slider";
import { cn } from "@/lib/utils";
import Link from "next/link";
import { AnalyticsChart } from "./components/analytics-chart";

// --- i18n & SETTINGS ---

const translations = {
  en: {
    // General
    email: "Email",
    password: "Password",
    actions: "Actions",
    status: "Status",
    role: "Role",
    save: "Save",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    search: "Search...",
    name: "Name",
    description: "Description",
    // Login
    adminPortal: "Admin Portal",
    adminPortalDesc: "Enter your credentials to access the dashboard.",
    logIn: "Log In",
    invalidCredentials: "Invalid email or password.",
    // Sidebar & View Keys
    dashboard: "Dashboard",
    reports: "Reports",
    userManagement: "User Management",
    threatMap: "Threat Map",
    settings: "Settings",
    logout: "Log Out",
    // Dashboard View
    totalScams: "Total Scams Detected",
    detectionRate: "Detection Rate",
    activeThreats: "Active Threats",
    userReports: "User Reports",
    scamAttemptsOverTime: "Scam Attempts Over Time",
    topScamCategories: "Top Scam Categories",
    liveThreatFeed: "Live Threat Feed",
    systemStatus: "System Status",
    scamOfTheDay: "Scam of the Day",
    scanUrl: "Scan URL",
    reportScam: "Report Scam",
    // Reports View
    generateNewReport: "Generate New Report",
    generateNewReportDesc:
      "Select the report type and date range to generate a new report.",
    reportType: "Report Type",
    dateRange: "Date Range",
    generateReport: "Generate Report",
    generating: "Generating...",
    generatedReports: "Generated Reports",
    reportName: "Report Name",
    dateGenerated: "Date Generated",
    generatedBy: "Generated By",
    download: "Download",
    // User Management View
    totalUsers: "Total Users",
    activeUsers: "Active Users",
    suspended: "Suspended",
    verifiedReporters: "Verified Reporters",
    userDirectory: "User Directory",
    userDirectoryDesc: "Manage, filter, and search all users in the system.",
    addUser: "Add User",
    topReporters: "Top Reporters",
    topReportersDesc: "Users with the most valid reports.",
    userRoleDistribution: "User Role Distribution",
    user: "User",
    trustScore: "Trust Score",
    riskLevel: "Risk Level",
    editUser: "Edit User",
    deleteUser: "Delete User",
    suspendUser: "Suspend User",
    restoreUser: "Restore User",
    // Settings View
    profile: "Profile",
    security: "Security",
    notifications: "Notifications",
    system: "System",
    profileInfo: "Profile Information",
    profileInfoDesc: "Manage your personal details.",
    fullName: "Full Name",
    emailAddress: "Email Address",
    changePassword: "Change Password",
    changePasswordDesc:
      "It's a good idea to use a strong password that you're not using elsewhere.",
    currentPassword: "Current Password",
    newPassword: "New Password",
    updatePassword: "Update Password",
    securitySettings: "Security Settings",
    securitySettingsDesc:
      "Configure 2FA, password policies, and manage active sessions.",
    twoFactorAuth: "Two-Factor Authentication (2FA)",
    twoFactorAuthDesc: "Add an extra layer of security to your account.",
    passwordPolicy: "Password Policy",
    activeSessions: "Active Sessions",
    activeSessionsDesc:
      "This is a list of devices that have logged into your account.",
    notificationSettings: "Notification Settings",
    notificationSettingsDesc: "Manage how you receive alerts and reports.",
    emailOnCritical: "Email on Critical Threat",
    emailOnCriticalDesc: "Receive an email for high-risk detections.",
    smsOnCritical: "SMS on Critical Threat",
    smsOnCriticalDesc: "Get an SMS for immediate, high-severity alerts.",
    weeklySummary: "Weekly Summary Report",
    weeklySummaryDesc: "Get a weekly digest of all threat activity.",
    alertSeverity: "Minimum Severity for Alerts",
    systemPreferences: "System & App Preferences",
    systemPreferencesDesc:
      "Customize the application's appearance and behavior.",
    theme: "Theme",
    themeDesc: "Switch between light and dark mode.",
    language: "Language",
    languageDesc: "Set your preferred language for the UI.",
    autoRefresh: "Dashboard Auto-Refresh",
    autoRefreshDesc: "Set how often live data should refresh.",
  },
  am: {
    // General
    email: "ኢሜይል",
    password: "የይለፍ ቃል",
    actions: "ድርጊቶች",
    status: "ሁኔታ",
    role: "ሚና",
    save: "አስቀምጥ",
    saveChanges: "ለውጦችን አስቀምጥ",
    cancel: "ሰርዝ",
    delete: "አጥፋ",
    edit: "አስተካክል",
    add: "ጨምር",
    search: "ፈልግ...",
    name: "ስም",
    description: "תיאור",
    // Login
    adminPortal: "የአስተዳዳሪ ፖርታል",
    adminPortalDesc: "ዳሽቦርዱን ለመድረስ ምስክርነቶችዎን ያስገቡ።",
    logIn: "ግባ",
    invalidCredentials: "የተሳሳተ ኢሜይል ወይም የይለፍ ቃል።",
    // Sidebar & View Keys
    dashboard: "ዳሽቦርድ",
    reports: "ሪፖርቶች",
    userManagement: "የተጠቃሚ አስተዳደር",
    threatMap: "የስጋት ካርታ",
    settings: "ቅንብሮች",
    logout: "ውጣ",
    // Dashboard View
    totalScams: "የተገኙ ማጭበርበሮች",
    detectionRate: "የመለየት መጠን",
    activeThreats: "በሂደት ላይ ያሉ ስጋቶች",
    userReports: "የተጠቃሚ ሪፖርቶች",
    scamAttemptsOverTime: "የማጭበርበር ሙከራዎች በጊዜ ሂደት",
    topScamCategories: "ዋና የማጭበርበር አይነቶች",
    liveThreatFeed: "የቀጥታ ስርጭት",
    systemStatus: "የስርዓት ሁኔታ",
    scamOfTheDay: "የእለቱ ማጭበርበር",
    scanUrl: "ዩአርኤልን ስካን አድርግ",
    reportScam: "ማጭበርበርን ሪፖርት አድርግ",
    // Reports View
    generateNewReport: "አዲስ ሪፖርት ይፍጠሩ",
    generateNewReportDesc: "አዲስ report ለመፍጠር የሪፖርቱን አይነት እና የቀን ክልል ይምረጡ።",
    reportType: "የሪፖርት አይነት",
    dateRange: "የቀን ክልል",
    generateReport: "ሪፖርት ይፍጠሩ",
    generating: "እየተፈጠረ ነው...",
    generatedReports: "የተፈጠሩ ሪፖርቶች",
    reportName: "የሪፖርት ስም",
    dateGenerated: "የተፈጠረበት ቀን",
    generatedBy: "የተፈጠረው በ",
    download: "አውርድ",
    // User Management View
    totalUsers: "ጠቅላላ ተጠቃሚዎች",
    activeUsers: "በሂደት ላይ ያሉ ተጠቃሚዎች",
    suspended: "የታገዱ",
    verifiedReporters: "የተረጋገጡ ሪፖርተሮች",
    userDirectory: "የተጠቃሚ ማውጫ",
    userDirectoryDesc: "በስርዓቱ ውስጥ ያሉትን ሁሉንም ተጠቃሚዎች ያስተዳድሩ፣ ያጣሩ እና ይፈልጉ።",
    addUser: "ተጠቃሚ ጨምር",
    topReporters: "ምርጥ ሪፖርተሮች",
    topReportersDesc: "ብዙ ትክክለኛ ሪፖርቶች ያላቸው ተጠቃሚዎች።",
    userRoleDistribution: "የተጠቃሚ ሚና ስርጭት",
    user: "ተጠቃሚ",
    trustScore: "የታማኝነት ነጥብ",
    riskLevel: "የአደጋ ደረጃ",
    editUser: "ተጠቃሚን አስተካክል",
    deleteUser: "ተጠቃሚን አጥፋ",
    suspendUser: "ተጠቃሚን አግድ",
    restoreUser: "ተጠቃሚን መልስ",
    // Settings View
    profile: "መገለጫ",
    security: "ደህንነት",
    notifications: "ማሳወቂያዎች",
    system: "ስርዓት",
    profileInfo: "የመገለጫ መረጃ",
    profileInfoDesc: "የግል ዝርዝሮችዎን ያስተዳድሩ።",
    fullName: "ሙሉ ስም",
    emailAddress: "የኢሜይል አድራሻ",
    changePassword: "የይለፍ ቃል ቀይር",
    changePasswordDesc: "በሌላ ቦታ የማይጠቀሙበትን ጠንካራ የይለፍ ቃል መጠቀም ጥሩ ሀሳብ ነው።",
    currentPassword: "የአሁኑ የይለፍ ቃል",
    newPassword: "አዲስ የይለፍ ቃል",
    updatePassword: "የይለፍ ቃል አዘምን",
    securitySettings: "የደህንነት ቅንብሮች",
    securitySettingsDesc: "2FA፣ የይለፍ ቃል ፖሊሲዎችን ያዋቅሩ እና ንቁ ክፍለ-ጊዜዎችን ያስተዳድሩ።",
    twoFactorAuth: "ባለ ሁለት-ደረጃ ማረጋገጫ (2FA)",
    twoFactorAuthDesc: "ለחשבונך ተጨማሪ የደህንነት ሽፋን ጨምር።",
    passwordPolicy: "የይለፍ ቃል መመሪያ",
    activeSessions: "ንቁ ክፍለ-ጊዜዎች",
    activeSessionsDesc: "ይህ ወደ חשבונך የገቡ የመሣሪያዎች ዝርዝር ነው።",
    notificationSettings: "የማሳወቂያ ቅንብሮች",
    notificationSettingsDesc: "ማንቂያዎችን እና ሪፖርቶችን እንዴት እንደሚቀበሉ ያስተዳድሩ።",
    emailOnCritical: "በከባድ ስጋት ላይ ኢሜይል",
    emailOnCriticalDesc: "ለከፍተኛ-አደጋ ግኝቶች ኢሜይል ተቀበል።",
    smsOnCritical: "በከባድ ስጋት ላይ ኤስኤምኤስ",
    smsOnCriticalDesc: "ለአስቸኳይ፣ ከፍተኛ-ከባድ ማንቂያዎች ኤስኤምኤስ ያግኙ።",
    weeklySummary: "ሳምንታዊ ማጠቃለያ ሪፖርት",
    weeklySummaryDesc: "የכל የስጋት እንቅስቃሴ ሳምንታዊ ማጠቃለያ ያግኙ።",
    alertSeverity: "ለማንቂያዎች ዝቅተኛው የክብደት ደረጃ",
    systemPreferences: "የስርዓት እና የመተግበሪያ ምርጫዎች",
    systemPreferencesDesc: "የመተግበሪያውን ገጽታ እና ባህሪ ያብጁ።",
    theme: "ገጽታ",
    themeDesc: "በብርሃን እና በጨለማ ሁነታ መካከል ይቀያይሩ።",
    language: "ቋንቋ",
    languageDesc: "ለ UI предпочитаемый ቋንቋዎን ያዘጋጁ።",
    autoRefresh: "ዳሽቦርድ ራስ-ሰር განახლება",
    autoRefreshDesc: "የቀጥታ ውሂብ ምን ያህል ጊዜ መновሳት እንዳለበት ያዘጋጁ።",
  },
};

type SettingsType = {
  name: string;
  email: string;
  twoFactor: boolean;
  passwordPolicy: "low" | "medium" | "high";
  emailOnCritical: boolean;
  smsOnCritical: boolean;
  weeklySummary: boolean;
  alertSeverity: "Low" | "Medium" | "High";
  theme: "light" | "dark" | "system";
  language: "en" | "am";
  refreshInterval: "15s" | "30s" | "60s" | "none";
};

const defaultSettings: SettingsType = {
  name: "Aphran Mohammed",
  email: "aphran@guardsphere.com",
  twoFactor: true,
  passwordPolicy: "medium",
  emailOnCritical: true,
  smsOnCritical: false,
  weeklySummary: true,
  alertSeverity: "High",
  theme: "system",
  language: "en",
  refreshInterval: "30s",
};

const SettingsContext = createContext<{
  settings: SettingsType;
  setSettings: React.Dispatch<React.SetStateAction<SettingsType>>;
}>({
  settings: defaultSettings,
  setSettings: () => {},
});

const useTranslations = () => {
  const { settings } = useContext(SettingsContext);
  const t = (key: keyof (typeof translations)["en"]) => {
    return translations[settings.language][key] || translations["en"][key];
  };
  return { t, language: settings.language };
};

function SettingsProvider({ children }: { children: React.ReactNode }) {
  const [settings, setSettings] = useState<SettingsType>(defaultSettings);

  useEffect(() => {
    const root = window.document.documentElement;
    const isDark =
      settings.theme === "dark" ||
      (settings.theme === "system" &&
        window.matchMedia("(prefers-color-scheme: dark)").matches);

    root.classList.toggle("dark", isDark);
  }, [settings.theme]);

  return (
    <SettingsContext.Provider value={{ settings, setSettings }}>
      {children}
    </SettingsContext.Provider>
  );
}

// --- INTERFACES ---
interface Report {
  id: number;
  name: string;
  date: string;
  by: string;
}

interface ManagedUser {
  id: number;
  name: string;
  email: string;
  role: "Admin" | "Analyst" | "User";
  lastActive: string;
  status: "Active" | "Suspended" | "Pending";
  isVerified: boolean;
  scamReports: number;
  trustScore: number; // 0-100
  riskLevel: "Low" | "Medium" | "High";
}

// --- LOGIN PAGE COMPONENT ---
function LoginPage({ onLoginSuccess }: { onLoginSuccess: () => void }) {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const [isLoading, setIsLoading] = useState(false);

  // Use a temporary t function for the login page
  const t = (key: keyof (typeof translations)["en"]) =>
    translations["en"][key] || key;

  const handleLogin = (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);
    setError("");

    setTimeout(() => {
      if (email === "admin@guardsphere.com" && password === "password") {
        onLoginSuccess();
      } else {
        setError(t("invalidCredentials"));
        setIsLoading(false);
      }
    }, 1000);
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-slate-100 font-sans p-4">
      <Card className="w-full max-w-sm shadow-2xl animate-in fade-in-50 duration-500">
        <CardHeader className="text-center">
          <div className="mx-auto mb-4 flex items-center justify-center h-16 w-16 bg-blue-100 rounded-full">
            <Shield className="h-8 w-8 text-blue-600" />
          </div>
          <CardTitle className="text-2xl">{t("adminPortal")}</CardTitle>
          <CardDescription>{t("adminPortalDesc")}</CardDescription>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleLogin} className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="email">{t("email")}</Label>
              <Input
                id="email"
                type="email"
                placeholder="admin@guardsphere.com"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                disabled={isLoading}
                required
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="password">{t("password")}</Label>
              <Input
                id="password"
                type="password"
                placeholder="••••••••"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                disabled={isLoading}
                required
              />
            </div>
            {error && (
              <div className="text-red-500 text-sm font-medium flex items-center">
                <AlertTriangle className="h-4 w-4 mr-2" />
                {error}
              </div>
            )}
            <Button type="submit" className="w-full" disabled={isLoading}>
              {isLoading ? (
                <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white"></div>
              ) : (
                t("logIn")
              )}
            </Button>
          </form>
        </CardContent>
      </Card>
    </div>
  );
}

// --- SIDEBAR COMPONENT ---
function Sidebar({
  activeView,
  setActiveView,
  onLogout,
}: {
  activeView: string;
  setActiveView: (view: string) => void;
  onLogout: () => void;
}) {
  const { t } = useTranslations();

  const navItems = [
    { key: "dashboard", icon: LayoutDashboard, label: t("dashboard") },
    { key: "reports", icon: BarChart3, label: t("reports") },
    { key: "userManagement", icon: Users, label: t("userManagement") },
    { key: "threatMap", icon: Globe, label: t("threatMap") },
    { key: "settings", icon: Settings, label: t("settings") },
  ];

  return (
    <aside className="w-64 flex-shrink-0 bg-gray-900 text-gray-300 flex flex-col">
      <div className="h-16 flex items-center justify-center px-4 border-b border-gray-800">
        <Link href="/" className="flex items-center space-x-2">
          <Shield className="h-8 w-8 text-blue-400" />
          <span className="text-2xl font-bold text-white">GuardSphere</span>
        </Link>
      </div>
      <nav className="flex-1 px-4 py-6 space-y-2">
        {navItems.map((item) => (
          <button
            key={item.key}
            onClick={() => setActiveView(item.key)}
            className="w-full flex items-center px-4 py-2.5 text-sm font-medium rounded-lg hover:bg-gray-800 hover:text-white transition-colors data-[active=true]:bg-blue-600 data-[active=true]:text-white"
            data-active={activeView === item.key}
          >
            <item.icon className="h-5 w-5 mr-3" />
            {item.label}
          </button>
        ))}
      </nav>
      <div className="px-4 py-4 border-t border-gray-800">
        <button
          onClick={onLogout}
          className="w-full flex items-center px-4 py-2.5 text-sm font-medium rounded-lg hover:bg-gray-800 hover:text-white transition-colors"
        >
          <LogOut className="h-5 w-5 mr-3" />
          {t("logout")}
        </button>
      </div>
    </aside>
  );
}

// --- REUSABLE KPI CARD COMPONENT ---
function KpiCard({
  title,
  value,
  subtitle,
  icon: Icon,
  colorClass,
}: {
  title: string;
  value: string;
  subtitle: string;
  icon: React.ElementType<LucideProps>;
  colorClass: string;
}) {
  return (
    <motion.div
      whileHover={{ y: -5, transition: { type: "spring", stiffness: 300 } }}
      whileTap={{ scale: 0.95 }}
      className="h-full"
    >
      <Card
        className={`h-full overflow-hidden border-l-4 bg-card transition-all duration-300 hover:shadow-lg ${colorClass}`}
      >
        <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
          <CardTitle className="text-sm font-medium text-muted-foreground">
            {title}
          </CardTitle>
          <Icon className="h-5 w-5 text-muted-foreground" />
        </CardHeader>
        <CardContent>
          <div className="text-3xl font-bold">{value}</div>
          <p className="text-xs text-muted-foreground">{subtitle}</p>
        </CardContent>
      </Card>
    </motion.div>
  );
}

// --- PROFESSIONAL VIEW COMPONENTS ---

// --- ReportsView ---
function ReportsView() {
  const { t } = useTranslations();
  const [date, setDate] = useState<DateRange | undefined>();
  const [reportType, setReportType] = useState<string>("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedReports, setGeneratedReports] = useState<Report[]>([
    { id: 1, name: "Q4 2023 Threat Summary", date: "2024-01-05", by: "Admin" },
    { id: 2, name: "December User Activity", date: "2024-01-02", by: "Admin" },
    {
      id: 3,
      name: "Weekly Performance Metrics",
      date: "2023-12-28",
      by: "System",
    },
  ]);

  const handleGenerateReport = () => {
    if (!reportType || !date?.from) {
      toast.error("Please select a report type and a date range.");
      return;
    }
    setIsGenerating(true);
    setTimeout(() => {
      const newReport: Report = {
        id: Date.now(),
        name: `${reportType} (${format(date.from!, "MMM d")} - ${
          date.to ? format(date.to, "MMM d") : ""
        })`,
        date: format(new Date(), "yyyy-MM-dd"),
        by: "Admin",
      };
      setGeneratedReports((prevReports) => [newReport, ...prevReports]);
      setIsGenerating(false);
      toast.success("New report has been generated successfully!");
      setDate(undefined);
      setReportType("");
    }, 1500);
  };

  const handleDownload = (report: Report) => {
    toast.info(`Generating PDF for: ${report.name}`);
    const doc = new jsPDF();
    doc.setFontSize(20);
    doc.text("GuardSphere Security Report", 14, 22);
    doc.setFontSize(12);
    doc.text(report.name, 14, 32);
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Generated on: ${report.date} by ${report.by}`, 14, 38);

    autoTable(doc, {
      startY: 50,
      head: [["Threat Type", "Count", "Severity", "Recommendation"]],
      body: [
        ["Phishing", "1,204", "High", "Block associated domains"],
        ["Malware", "345", "High", "Isolate affected systems"],
        ["Suspicious Login", "5,678", "Medium", "Require user password reset"],
        ["Spam", "10,982", "Low", "Update spam filter rules"],
        ["Social Engineering", "88", "High", "User training required"],
      ],
      theme: "striped",
      headStyles: { fillColor: [22, 163, 74] },
    });

    const finalY = (doc as any).lastAutoTable.finalY;
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text(
      "This is an auto-generated report. Do not reply.",
      14,
      finalY + 10
    );
    doc.save(`${report.name.replace(/ /g, "_")}.pdf`);
  };

  return (
    <div className="flex-1 p-6 lg:p-8 space-y-8 animate-in fade-in-50 duration-500">
      <Card>
        <CardHeader>
          <CardTitle>{t("generateNewReport")}</CardTitle>
          <CardDescription>{t("generateNewReportDesc")}</CardDescription>
        </CardHeader>
        <CardContent className="grid grid-cols-1 md:grid-cols-3 gap-4 items-end">
          <div className="space-y-2">
            <Label htmlFor="report-type">{t("reportType")}</Label>
            <Select value={reportType} onValueChange={setReportType}>
              <SelectTrigger id="report-type">
                <SelectValue placeholder="Select a report" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="Threat Summary">Threat Summary</SelectItem>
                <SelectItem value="User Activity">User Activity</SelectItem>
                <SelectItem value="System Performance">
                  System Performance
                </SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div className="space-y-2">
            <Label htmlFor="date-range">{t("dateRange")}</Label>
            <Popover>
              <PopoverTrigger asChild>
                <Button
                  id="date-range"
                  variant={"outline"}
                  className={cn(
                    "w-full justify-start text-left font-normal",
                    !date && "text-muted-foreground"
                  )}
                >
                  <CalendarIcon className="mr-2 h-4 w-4" />
                  {date?.from ? (
                    date.to ? (
                      <>
                        {format(date.from, "LLL dd, y")} -{" "}
                        {format(date.to, "LLL dd, y")}
                      </>
                    ) : (
                      format(date.from, "LLL dd, y")
                    )
                  ) : (
                    <span>Pick a date</span>
                  )}
                </Button>
              </PopoverTrigger>
              <PopoverContent className="w-auto p-0" align="start">
                <Calendar
                  initialFocus
                  mode="range"
                  defaultMonth={date?.from}
                  selected={date}
                  onSelect={setDate}
                  numberOfMonths={2}
                />
              </PopoverContent>
            </Popover>
          </div>
          <Button
            onClick={handleGenerateReport}
            disabled={isGenerating}
            className="w-full md:w-auto"
          >
            {isGenerating ? (
              <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-primary-foreground mr-2"></div>
            ) : (
              <FileText className="mr-2 h-4 w-4" />
            )}
            {isGenerating ? t("generating") : t("generateReport")}
          </Button>
        </CardContent>
      </Card>
      <Card>
        <CardHeader>
          <CardTitle>{t("generatedReports")}</CardTitle>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>{t("reportName")}</TableHead>
                <TableHead>{t("dateGenerated")}</TableHead>
                <TableHead>{t("generatedBy")}</TableHead>
                <TableHead className="text-right">{t("actions")}</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {generatedReports.map((report) => (
                <TableRow key={report.id}>
                  <TableCell className="font-medium">{report.name}</TableCell>
                  <TableCell>{report.date}</TableCell>
                  <TableCell>{report.by}</TableCell>
                  <TableCell className="text-right">
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => handleDownload(report)}
                    >
                      <Download className="mr-2 h-4 w-4" />
                      {t("download")}
                    </Button>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
}

// --- UserFormDialog ---
function UserFormDialog({
  open,
  onOpenChange,
  user,
  onSave,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  user: ManagedUser | null;
  onSave: (data: {
    name: string;
    email: string;
    role: ManagedUser["role"];
  }) => void;
}) {
  const { t } = useTranslations();
  const [formData, setFormData] = useState({
    name: "",
    email: "",
    role: "User" as ManagedUser["role"],
  });

  useEffect(() => {
    if (user) {
      setFormData({ name: user.name, email: user.email, role: user.role });
    } else {
      setFormData({ name: "", email: "", role: "User" });
    }
  }, [user, open]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!formData.name || !formData.email) {
      toast.error("Please fill out all required fields.");
      return;
    }
    onSave(formData);
    onOpenChange(false);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>{user ? t("editUser") : t("addUser")}</DialogTitle>
          <DialogDescription>
            {user
              ? `Update the details for ${user.name}.`
              : "Enter the details for the new user."}
          </DialogDescription>
        </DialogHeader>
        <form onSubmit={handleSubmit} className="grid gap-4 py-4">
          <div className="space-y-2">
            <Label htmlFor="name">{t("fullName")}</Label>
            <Input
              id="name"
              value={formData.name}
              onChange={(e) =>
                setFormData({ ...formData, name: e.target.value })
              }
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="email">{t("emailAddress")}</Label>
            <Input
              id="email"
              type="email"
              value={formData.email}
              onChange={(e) =>
                setFormData({ ...formData, email: e.target.value })
              }
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="role">{t("role")}</Label>
            <Select
              value={formData.role}
              onValueChange={(value) =>
                setFormData({ ...formData, role: value as ManagedUser["role"] })
              }
            >
              <SelectTrigger id="role">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="User">User</SelectItem>
                <SelectItem value="Analyst">Analyst</SelectItem>
                <SelectItem value="Admin">Admin</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <DialogFooter>
            <Button type="submit">
              {user ? t("saveChanges") : t("addUser")}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}

// --- UserManagementView ---
function UserManagementView() {
  const { t } = useTranslations();
  const [users, setUsers] = useState<ManagedUser[]>([
    {
      id: 1,
      name: "Aphran Mohammed",
      email: "aphran@guardsphere.com",
      role: "Admin",
      lastActive: "2 min ago",
      status: "Active",
      isVerified: true,
      scamReports: 12,
      trustScore: 98,
      riskLevel: "Low",
    },
    {
      id: 2,
      name: "Nahom Bekele",
      email: "nahom.b@example.com",
      role: "Analyst",
      lastActive: "1 hour ago",
      status: "Active",
      isVerified: true,
      scamReports: 45,
      trustScore: 92,
      riskLevel: "Low",
    },
    {
      id: 3,
      name: "Dawit Addis",
      email: "dawit.a@example.com",
      role: "User",
      lastActive: "3 days ago",
      status: "Active",
      isVerified: false,
      scamReports: 5,
      trustScore: 75,
      riskLevel: "Medium",
    },
    {
      id: 4,
      name: "Meron Nisrane",
      email: "meron.n@example.com",
      role: "User",
      lastActive: "2 weeks ago",
      status: "Suspended",
      isVerified: false,
      scamReports: 23,
      trustScore: 34,
      riskLevel: "High",
    },
    {
      id: 5,
      name: "Amanuel",
      email: "amanuel@example.com",
      role: "User",
      lastActive: "1 month ago",
      status: "Active",
      isVerified: false,
      scamReports: 2,
      trustScore: 65,
      riskLevel: "Medium",
    },
    {
      id: 6,
      name: "New User",
      email: "new.user@example.com",
      role: "User",
      lastActive: "Never",
      status: "Pending",
      isVerified: false,
      scamReports: 0,
      trustScore: 50,
      riskLevel: "Medium",
    },
  ]);

  const [searchTerm, setSearchTerm] = useState("");
  const [statusFilter, setStatusFilter] = useState("all");
  const [roleFilter, setRoleFilter] = useState("all");
  const [isUserDialogOpen, setIsUserDialogOpen] = useState(false);
  const [editingUser, setEditingUser] = useState<ManagedUser | null>(null);

  const filteredUsers = useMemo(() => {
    return users.filter(
      (user) =>
        (user.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
          user.email.toLowerCase().includes(searchTerm.toLowerCase())) &&
        (statusFilter === "all" || user.status === statusFilter) &&
        (roleFilter === "all" || user.role === roleFilter)
    );
  }, [users, searchTerm, statusFilter, roleFilter]);

  const kpiData = useMemo(
    () => ({
      total: users.length,
      active: users.filter((u) => u.status === "Active").length,
      suspended: users.filter((u) => u.status === "Suspended").length,
      verified: users.filter((u) => u.isVerified).length,
    }),
    [users]
  );

  const roleDistribution = useMemo(() => {
    const counts = users.reduce((acc, user) => {
      acc[user.role] = (acc[user.role] || 0) + 1;
      return acc;
    }, {} as Record<ManagedUser["role"], number>);
    return Object.entries(counts).map(([name, value]) => ({ name, value }));
  }, [users]);

  const topReporters = useMemo(
    () => [...users].sort((a, b) => b.scamReports - a.scamReports).slice(0, 3),
    [users]
  );

  const handleOpenAddDialog = () => {
    setEditingUser(null);
    setIsUserDialogOpen(true);
  };

  const handleOpenEditDialog = (user: ManagedUser) => {
    setEditingUser(user);
    setIsUserDialogOpen(true);
  };

  const handleSaveUser = (formData: {
    name: string;
    email: string;
    role: ManagedUser["role"];
  }) => {
    if (editingUser) {
      setUsers(
        users.map((u) => (u.id === editingUser.id ? { ...u, ...formData } : u))
      );
      toast.success(`User "${formData.name}" has been updated.`);
    } else {
      const newUser: ManagedUser = {
        id: Date.now(),
        ...formData,
        lastActive: "Just now",
        status: "Active",
        isVerified: false,
        scamReports: 0,
        trustScore: 50,
        riskLevel: "Medium",
      };
      setUsers([newUser, ...users]);
      toast.success(`New user "${formData.name}" has been created.`);
    }
  };

  const handleDeleteUser = (userId: number) => {
    if (confirm("Are you sure you want to permanently delete this user?")) {
      const userName = users.find((u) => u.id === userId)?.name;
      setUsers(users.filter((u) => u.id !== userId));
      toast.error(`User "${userName}" has been deleted.`);
    }
  };

  const handleStatusChange = (
    userId: number,
    newStatus: ManagedUser["status"]
  ) => {
    setUsers(
      users.map((u) => (u.id === userId ? { ...u, status: newStatus } : u))
    );
    toast.success(`User status updated to ${newStatus}.`);
  };

  const getRiskColor = (level: ManagedUser["riskLevel"]) => {
    if (level === "High") return "text-red-600";
    if (level === "Medium") return "text-yellow-600";
    return "text-green-600";
  };

  const getStatusColor = (status: ManagedUser["status"]) => {
    if (status === "Active") return "bg-green-100 text-green-800";
    if (status === "Suspended") return "bg-red-100 text-red-800";
    return "bg-yellow-100 text-yellow-800";
  };

  const COLORS = ["#0088FE", "#00C49F", "#FFBB28"];

  return (
    <>
      <div className="flex-1 p-6 lg:p-8 space-y-8 animate-in fade-in-50 duration-500">
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          <KpiCard
            title={t("totalUsers")}
            value={kpiData.total.toString()}
            subtitle="All accounts"
            icon={Users}
            colorClass="border-blue-500"
          />
          <KpiCard
            title={t("activeUsers")}
            value={kpiData.active.toString()}
            subtitle="Currently active"
            icon={UserCheck}
            colorClass="border-green-500"
          />
          <KpiCard
            title={t("suspended")}
            value={kpiData.suspended.toString()}
            subtitle="Restricted accounts"
            icon={UserX}
            colorClass="border-red-500"
          />
          <KpiCard
            title={t("verifiedReporters")}
            value={kpiData.verified.toString()}
            subtitle="Trusted contributors"
            icon={ShieldCheck}
            colorClass="border-sky-500"
          />
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          <div className="lg:col-span-2">
            <Card>
              <CardHeader className="flex flex-row items-center justify-between">
                <div>
                  <CardTitle>{t("userDirectory")}</CardTitle>
                  <CardDescription>{t("userDirectoryDesc")}</CardDescription>
                </div>
                <Button onClick={handleOpenAddDialog}>
                  <PlusCircle className="mr-2 h-4 w-4" />
                  {t("addUser")}
                </Button>
              </CardHeader>
              <CardContent>
                <div className="flex items-center gap-4 py-4">
                  <div className="relative flex-1">
                    <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                    <Input
                      placeholder={t("search")}
                      className="pl-10"
                      value={searchTerm}
                      onChange={(e) => setSearchTerm(e.target.value)}
                    />
                  </div>
                  <Select value={statusFilter} onValueChange={setStatusFilter}>
                    <SelectTrigger className="w-[180px]">
                      <SelectValue placeholder="Filter by Status" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="all">All Statuses</SelectItem>
                      <SelectItem value="Active">Active</SelectItem>
                      <SelectItem value="Suspended">Suspended</SelectItem>
                      <SelectItem value="Pending">Pending</SelectItem>
                    </SelectContent>
                  </Select>
                  <Select value={roleFilter} onValueChange={setRoleFilter}>
                    <SelectTrigger className="w-[180px]">
                      <SelectValue placeholder="Filter by Role" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="all">All Roles</SelectItem>
                      <SelectItem value="Admin">Admin</SelectItem>
                      <SelectItem value="Analyst">Analyst</SelectItem>
                      <SelectItem value="User">User</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead className="w-[50px]">
                        <Checkbox />
                      </TableHead>
                      <TableHead>{t("user")}</TableHead>
                      <TableHead>{t("trustScore")}</TableHead>
                      <TableHead>{t("riskLevel")}</TableHead>
                      <TableHead>{t("status")}</TableHead>
                      <TableHead className="text-right">
                        {t("reports")}
                      </TableHead>
                      <TableHead className="text-right">
                        {t("actions")}
                      </TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {filteredUsers.map((user) => (
                      <TableRow key={user.id}>
                        <TableCell>
                          <Checkbox />
                        </TableCell>
                        <TableCell>
                          <div className="flex items-center gap-2">
                            {user.isVerified && (
                              <ShieldCheck className="h-4 w-4 text-sky-500" />
                            )}
                            <div>
                              <div className="font-medium">{user.name}</div>
                              <div className="text-sm text-muted-foreground">
                                {user.email}
                              </div>
                            </div>
                          </div>
                        </TableCell>
                        <TableCell>
                          <div className="flex items-center gap-2">
                            <Progress
                              value={user.trustScore}
                              className="h-2 w-20"
                            />
                            <span className="text-xs text-muted-foreground">
                              {user.trustScore}%
                            </span>
                          </div>
                        </TableCell>
                        <TableCell>
                          <span
                            className={`font-medium ${getRiskColor(
                              user.riskLevel
                            )}`}
                          >
                            {user.riskLevel}
                          </span>
                        </TableCell>
                        <TableCell>
                          <Badge
                            variant="outline"
                            className={getStatusColor(user.status)}
                          >
                            {user.status}
                          </Badge>
                        </TableCell>
                        <TableCell className="text-right font-medium">
                          {user.scamReports}
                        </TableCell>
                        <TableCell className="text-right">
                          <DropdownMenu>
                            <DropdownMenuTrigger asChild>
                              <Button variant="ghost" className="h-8 w-8 p-0">
                                <span className="sr-only">Open menu</span>
                                <MoreHorizontal className="h-4 w-4" />
                              </Button>
                            </DropdownMenuTrigger>
                            <DropdownMenuContent align="end">
                              <DropdownMenuLabel>
                                {t("actions")}
                              </DropdownMenuLabel>
                              <DropdownMenuItem
                                onClick={() => handleOpenEditDialog(user)}
                              >
                                {t("editUser")}
                              </DropdownMenuItem>
                              {user.status === "Active" && (
                                <DropdownMenuItem
                                  className="text-yellow-600"
                                  onClick={() =>
                                    handleStatusChange(user.id, "Suspended")
                                  }
                                >
                                  {t("suspendUser")}
                                </DropdownMenuItem>
                              )}
                              {user.status === "Suspended" && (
                                <DropdownMenuItem
                                  className="text-green-600"
                                  onClick={() =>
                                    handleStatusChange(user.id, "Active")
                                  }
                                >
                                  {t("restoreUser")}
                                </DropdownMenuItem>
                              )}
                              <DropdownMenuSeparator />
                              <DropdownMenuItem
                                className="text-red-600"
                                onClick={() => handleDeleteUser(user.id)}
                              >
                                {t("deleteUser")}
                              </DropdownMenuItem>
                            </DropdownMenuContent>
                          </DropdownMenu>
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </CardContent>
            </Card>
          </div>
          <div className="space-y-8">
            <Card>
              <CardHeader>
                <CardTitle>{t("topReporters")}</CardTitle>
                <CardDescription>{t("topReportersDesc")}</CardDescription>
              </CardHeader>
              <CardContent>
                <ul className="space-y-4">
                  {topReporters.map((user, index) => (
                    <li
                      key={user.id}
                      className="flex items-center justify-between"
                    >
                      <div className="flex items-center gap-3">
                        <span className="font-bold text-lg text-muted-foreground">
                          {index + 1}
                        </span>
                        <div>
                          <p className="font-medium">{user.name}</p>
                          <p className="text-sm text-muted-foreground">
                            {user.role}
                          </p>
                        </div>
                      </div>
                      <div className="text-right">
                        <p className="font-bold">{user.scamReports}</p>
                        <p className="text-xs text-muted-foreground">
                          {t("reports")}
                        </p>
                      </div>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>{t("userRoleDistribution")}</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="w-full h-[200px]">
                  <ResponsiveContainer width="100%" height="100%">
                    <PieChart>
                      <Pie
                        data={roleDistribution}
                        dataKey="value"
                        nameKey="name"
                        cx="50%"
                        cy="50%"
                        outerRadius={80}
                        label
                      >
                        {roleDistribution.map((entry, index) => (
                          <Cell
                            key={`cell-${index}`}
                            fill={COLORS[index % COLORS.length]}
                          />
                        ))}
                      </Pie>
                      <RechartsTooltip />
                    </PieChart>
                  </ResponsiveContainer>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
      <UserFormDialog
        open={isUserDialogOpen}
        onOpenChange={setIsUserDialogOpen}
        user={editingUser}
        onSave={handleSaveUser}
      />
    </>
  );
}

// --- ThreatMapView ---
const geoUrl =
  "https://raw.githubusercontent.com/deldersveld/topojson/master/countries/ethiopia/ethiopia-and-neighbors.json";

const locations = {
  "Addis Ababa": {
    coordinates: [38.7578, 9.0227] as [number, number],
    type: "City",
  },
  "Dire Dawa": { coordinates: [41.85, 9.6] as [number, number], type: "City" },
  Mekelle: { coordinates: [39.4667, 13.5] as [number, number], type: "City" },
  "Bahir Dar": {
    coordinates: [37.3833, 11.6] as [number, number],
    type: "City",
  },
  Hawassa: { coordinates: [38.4667, 7.05] as [number, number], type: "City" },
  Nairobi: {
    coordinates: [36.8219, -1.2921] as [number, number],
    type: "External",
  },
  Dubai: {
    coordinates: [55.2708, 25.2048] as [number, number],
    type: "External",
  },
  Guangzhou: {
    coordinates: [113.2644, 23.1291] as [number, number],
    type: "External",
  },
  "Washington DC": {
    coordinates: [-77.0369, 38.9072] as [number, number],
    type: "External",
  },
};

type Threat = {
  id: number;
  origin: keyof typeof locations;
  target: keyof typeof locations;
  type: "Email" | "SMS" | "Social Media" | "Fake Website";
  severity: "Low" | "Medium" | "High";
  timestamp: number; // hours ago
  targetInstitution?: string;
};

const allThreats: Threat[] = [
  {
    id: 1,
    origin: "Dubai",
    target: "Addis Ababa",
    type: "Fake Website",
    severity: "High",
    timestamp: 1,
    targetInstitution: "Bank of Abyssinia",
  },
  {
    id: 2,
    origin: "Guangzhou",
    target: "Addis Ababa",
    type: "Email",
    severity: "High",
    timestamp: 2,
    targetInstitution: "Ethio Telecom",
  },
  {
    id: 3,
    origin: "Addis Ababa",
    target: "Nairobi",
    type: "SMS",
    severity: "Medium",
    timestamp: 3,
  },
  {
    id: 4,
    origin: "Washington DC",
    target: "Mekelle",
    type: "Social Media",
    severity: "Low",
    timestamp: 5,
  },
  {
    id: 5,
    origin: "Bahir Dar",
    target: "Hawassa",
    type: "Email",
    severity: "Medium",
    timestamp: 8,
  },
  {
    id: 6,
    origin: "Dubai",
    target: "Dire Dawa",
    type: "Fake Website",
    severity: "High",
    timestamp: 10,
    targetInstitution: "CBE",
  },
  {
    id: 7,
    origin: "Guangzhou",
    target: "Bahir Dar",
    type: "SMS",
    severity: "Medium",
    timestamp: 12,
  },
];

function ThreatMapView() {
  const [threatTypeFilter, setThreatTypeFilter] = useState("all");
  const [severityFilter, setSeverityFilter] = useState("all");
  const [timeFilter, setTimeFilter] = useState([24]);

  const filteredThreats = useMemo(() => {
    return allThreats.filter(
      (threat) =>
        (threatTypeFilter === "all" || threat.type === threatTypeFilter) &&
        (severityFilter === "all" || threat.severity === severityFilter) &&
        threat.timestamp <= timeFilter[0]
    );
  }, [threatTypeFilter, severityFilter, timeFilter]);

  const getSeverityColor = (severity: Threat["severity"]) => {
    if (severity === "High") return "#ef4444"; // red-500
    if (severity === "Medium") return "#f97316"; // orange-500
    return "#eab308"; // yellow-500
  };

  const topOrigins = useMemo(() => {
    const counts = filteredThreats.reduce((acc, t) => {
      acc[t.origin] = (acc[t.origin] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);
    return Object.entries(counts)
      .sort(([, a], [, b]) => b - a)
      .slice(0, 5);
  }, [filteredThreats]);

  const topTargets = useMemo(() => {
    const institutions = filteredThreats
      .map((t) => t.targetInstitution)
      .filter((t): t is string => !!t);
    const counts = institutions.reduce((acc, t) => {
      acc[t] = (acc[t] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);
    return Object.entries(counts)
      .sort(([, a], [, b]) => b - a)
      .slice(0, 5);
  }, [filteredThreats]);

  return (
    <div className="flex-1 p-4 md:p-6 lg:p-8 grid grid-cols-1 lg:grid-cols-4 gap-6 animate-in fade-in-50 duration-500 h-[calc(100vh-4rem)] bg-background">
      {/* Main Map Content */}
      <div className="lg:col-span-3 bg-slate-800/90 dark:bg-slate-900/90 border border-slate-700/50 rounded-lg overflow-hidden relative flex flex-col shadow-2xl">
        <div className="p-4 border-b border-slate-700/50">
          <h3 className="text-white font-semibold">
            Regional Threat Activity: Ethiopia
          </h3>
        </div>
        <div className="flex-1 relative bg-grid-slate-700/[0.05]">
          <div className="absolute inset-0 bg-gradient-to-b from-slate-900/50 to-slate-900" />
          <div className="animate-scanline"></div>
          <ComposableMap
            projection="geoMercator"
            projectionConfig={{
              center: [40, 9], // Center on Ethiopia
              scale: 2200,
            }}
            className="w-full h-full"
          >
            <Geographies geography={geoUrl}>
              {({ geographies }) =>
                geographies.map((geo) => {
                  const isEthiopia = geo.properties.NAME_EN === "Ethiopia";
                  return (
                    <Geography
                      key={geo.rsmKey}
                      geography={geo}
                      fill={isEthiopia ? "#1e293b" : "#0f172a"} // Darker fill for Ethiopia
                      stroke="#334155" // slate-700
                      strokeWidth={0.5}
                    />
                  );
                })
              }
            </Geographies>
            {filteredThreats.map((threat) => (
              <Line
                key={`line-${threat.id}`}
                from={locations[threat.origin].coordinates}
                to={locations[threat.target].coordinates}
                stroke={getSeverityColor(threat.severity)}
                strokeWidth={2}
                strokeLinecap="round"
                className="animate-comet"
                style={{
                  filter: `drop-shadow(0 0 3px ${getSeverityColor(
                    threat.severity
                  )})`,
                  animationDelay: `${threat.id * 0.2}s`,
                }}
              />
            ))}
            {Object.entries(locations).map(([name, { coordinates, type }]) => (
              <Marker key={name} coordinates={coordinates}>
                <motion.circle
                  r={type === "City" ? 4 : 6}
                  fill={type === "City" ? "#38bdf8" : "#fde047"} // sky-400 for cities, yellow-400 for external
                  stroke="#fff"
                  strokeWidth={1}
                  className="animate-pulse-strong"
                  style={{
                    filter: `drop-shadow(0 0 8px ${
                      type === "City" ? "#38bdf8" : "#fde047"
                    })`,
                  }}
                />
                <text
                  textAnchor="middle"
                  y={-10}
                  className="text-xs fill-slate-300 font-sans"
                >
                  {name}
                </text>
              </Marker>
            ))}
          </ComposableMap>
        </div>
        <div className="p-2 border-t border-slate-700/50 bg-black/20 text-white text-sm overflow-hidden h-10 flex items-center">
          <span className="font-bold text-red-500 mr-4 flex-shrink-0 px-2">
            LIVE FEED:
          </span>
          <div className="animate-ticker whitespace-nowrap">
            {allThreats.map((t) => (
              <span key={t.id} className="mr-12">
                <span
                  style={{ color: getSeverityColor(t.severity) }}
                  className="font-semibold"
                >
                  [{t.severity.toUpperCase()}]
                </span>{" "}
                {t.type} attack from {t.origin} targeting {t.target}
                {t.targetInstitution && ` (${t.targetInstitution})`}.
              </span>
            ))}
            {/* Duplicate for seamless loop */}
            {allThreats.map((t) => (
              <span key={`dup-${t.id}`} className="mr-12">
                <span
                  style={{ color: getSeverityColor(t.severity) }}
                  className="font-semibold"
                >
                  [{t.severity.toUpperCase()}]
                </span>{" "}
                {t.type} attack from {t.origin} targeting {t.target}
                {t.targetInstitution && ` (${t.targetInstitution})`}.
              </span>
            ))}
          </div>
        </div>
      </div>

      {/* Sidebar with Filters and Stats */}
      <div className="lg:col-span-1 space-y-6 flex flex-col">
        <Card>
          <CardHeader>
            <CardTitle>Threat Filters</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <Label>Threat Type</Label>
              <Select
                value={threatTypeFilter}
                onValueChange={setThreatTypeFilter}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Types</SelectItem>
                  <SelectItem value="Email">Email</SelectItem>
                  <SelectItem value="SMS">SMS</SelectItem>
                  <SelectItem value="Social Media">Social Media</SelectItem>
                  <SelectItem value="Fake Website">Fake Website</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div>
              <Label>Severity</Label>
              <Select value={severityFilter} onValueChange={setSeverityFilter}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Severities</SelectItem>
                  <SelectItem value="Low">Low</SelectItem>
                  <SelectItem value="Medium">Medium</SelectItem>
                  <SelectItem value="High">High</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div>
              <Label>Time Range (Last {timeFilter[0]} hours)</Label>
              <Slider
                defaultValue={[24]}
                max={24}
                step={1}
                min={1}
                onValueChange={setTimeFilter}
              />
            </div>
          </CardContent>
        </Card>

        <Card className="flex-1">
          <CardHeader>
            <CardTitle>Local Intelligence</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4 text-sm">
            <div className="flex justify-between">
              <span>Threats in Range</span>
              <span className="font-bold">{filteredThreats.length}</span>
            </div>
            <div>
              <h4 className="font-semibold mb-2">Top Origins</h4>
              <ul className="space-y-1">
                {topOrigins.map(([country, count]) => (
                  <li key={country} className="flex justify-between">
                    <span>{country}</span>
                    <span className="font-mono">{count}</span>
                  </li>
                ))}
              </ul>
            </div>
            <div>
              <h4 className="font-semibold mb-2">Top Targeted Institutions</h4>
              <ul className="space-y-1">
                {topTargets.map(([name, count]) => (
                  <li key={name} className="flex justify-between">
                    <span>{name}</span>
                    <span className="font-mono">{count}</span>
                  </li>
                ))}
              </ul>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

// --- SettingsView ---
function SettingsView() {
  const { t } = useTranslations();
  const { settings, setSettings } = useContext(SettingsContext);

  const handleSettingChange = (key: keyof SettingsType, value: any) => {
    setSettings((prev) => ({ ...prev, [key]: value }));
    toast.success("Setting updated!");
  };

  // Mock data for active sessions
  const activeSessions = [
    {
      id: 1,
      device: "Chrome on Windows",
      ip: "192.168.1.10",
      lastSeen: "2 minutes ago",
      isCurrent: true,
    },
    {
      id: 2,
      device: "Safari on iPhone",
      ip: "103.22.5.12",
      lastSeen: "3 hours ago",
      isCurrent: false,
    },
  ];

  return (
    <div className="flex-1 p-6 lg:p-8 animate-in fade-in-50 duration-500">
      <Tabs defaultValue="system" className="w-full">
        <TabsList className="grid w-full grid-cols-4">
          <TabsTrigger value="profile">{t("profile")}</TabsTrigger>
          <TabsTrigger value="security">{t("security")}</TabsTrigger>
          <TabsTrigger value="notifications">{t("notifications")}</TabsTrigger>
          <TabsTrigger value="system">{t("system")}</TabsTrigger>
        </TabsList>

        {/* Profile Tab */}
        <TabsContent value="profile">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="md:col-span-2">
              <Card>
                <CardHeader>
                  <CardTitle>{t("profileInfo")}</CardTitle>
                  <CardDescription>{t("profileInfoDesc")}</CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="space-y-2">
                    <Label htmlFor="name">{t("fullName")}</Label>
                    <Input
                      id="name"
                      defaultValue={settings.name}
                      onChange={(e) =>
                        handleSettingChange("name", e.target.value)
                      }
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="email">{t("emailAddress")}</Label>
                    <Input
                      id="email"
                      type="email"
                      defaultValue={settings.email}
                      onChange={(e) =>
                        handleSettingChange("email", e.target.value)
                      }
                    />
                  </div>
                  <Button
                    onClick={() => toast.success("Profile information saved!")}
                  >
                    {t("saveChanges")}
                  </Button>
                </CardContent>
              </Card>
              <Card className="mt-8">
                <CardHeader>
                  <CardTitle>{t("changePassword")}</CardTitle>
                  <CardDescription>{t("changePasswordDesc")}</CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="space-y-2">
                    <Label htmlFor="current-password">
                      {t("currentPassword")}
                    </Label>
                    <Input id="current-password" type="password" />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="new-password">{t("newPassword")}</Label>
                    <Input id="new-password" type="password" />
                  </div>
                  <Button
                    onClick={() =>
                      toast.success("Password changed successfully!")
                    }
                  >
                    {t("updatePassword")}
                  </Button>
                </CardContent>
              </Card>
            </div>
          </div>
        </TabsContent>

        {/* Security Tab */}
        <TabsContent value="security">
          <Card>
            <CardHeader>
              <CardTitle>{t("securitySettings")}</CardTitle>
              <CardDescription>{t("securitySettingsDesc")}</CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="flex items-center justify-between rounded-lg border p-4">
                <div>
                  <h4 className="font-medium">{t("twoFactorAuth")}</h4>
                  <p className="text-sm text-muted-foreground">
                    {t("twoFactorAuthDesc")}
                  </p>
                </div>
                <Switch
                  checked={settings.twoFactor}
                  onCheckedChange={(checked) =>
                    handleSettingChange("twoFactor", checked)
                  }
                />
              </div>
              <div className="space-y-2">
                <Label>{t("passwordPolicy")}</Label>
                <Select
                  value={settings.passwordPolicy}
                  onValueChange={(value: SettingsType["passwordPolicy"]) =>
                    handleSettingChange("passwordPolicy", value)
                  }
                >
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="low">Low (8+ characters)</SelectItem>
                    <SelectItem value="medium">
                      Medium (12+ characters, 1 number)
                    </SelectItem>
                    <SelectItem value="high">
                      High (16+ characters, 1 number, 1 symbol)
                    </SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </CardContent>
          </Card>
          <Card className="mt-6">
            <CardHeader>
              <CardTitle>{t("activeSessions")}</CardTitle>
              <CardDescription>{t("activeSessionsDesc")}</CardDescription>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Device</TableHead>
                    <TableHead>IP Address</TableHead>
                    <TableHead>Last Seen</TableHead>
                    <TableHead className="text-right">{t("actions")}</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {activeSessions.map((session) => (
                    <TableRow key={session.id}>
                      <TableCell className="font-medium">
                        {session.device}{" "}
                        {session.isCurrent && (
                          <Badge variant="outline" className="ml-2">
                            This device
                          </Badge>
                        )}
                      </TableCell>
                      <TableCell>{session.ip}</TableCell>
                      <TableCell>{session.lastSeen}</TableCell>
                      <TableCell className="text-right">
                        {!session.isCurrent && (
                          <Button
                            variant="destructive"
                            size="sm"
                            onClick={() =>
                              toast.error(
                                `Session from ${session.device} has been logged out.`
                              )
                            }
                          >
                            {t("logout")}
                          </Button>
                        )}
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </TabsContent>

        {/* Notifications Tab */}
        <TabsContent value="notifications">
          <Card>
            <CardHeader>
              <CardTitle>{t("notificationSettings")}</CardTitle>
              <CardDescription>{t("notificationSettingsDesc")}</CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="flex items-center justify-between rounded-lg border p-4">
                <div>
                  <h4 className="font-medium">{t("emailOnCritical")}</h4>
                  <p className="text-sm text-muted-foreground">
                    {t("emailOnCriticalDesc")}
                  </p>
                </div>
                <Switch
                  checked={settings.emailOnCritical}
                  onCheckedChange={(checked) =>
                    handleSettingChange("emailOnCritical", checked)
                  }
                />
              </div>
              <div className="flex items-center justify-between rounded-lg border p-4">
                <div>
                  <h4 className="font-medium">{t("smsOnCritical")}</h4>
                  <p className="text-sm text-muted-foreground">
                    {t("smsOnCriticalDesc")}
                  </p>
                </div>
                <Switch
                  checked={settings.smsOnCritical}
                  onCheckedChange={(checked) =>
                    handleSettingChange("smsOnCritical", checked)
                  }
                />
              </div>
              <div className="flex items-center justify-between rounded-lg border p-4">
                <div>
                  <h4 className="font-medium">{t("weeklySummary")}</h4>
                  <p className="text-sm text-muted-foreground">
                    {t("weeklySummaryDesc")}
                  </p>
                </div>
                <Switch
                  checked={settings.weeklySummary}
                  onCheckedChange={(checked) =>
                    handleSettingChange("weeklySummary", checked)
                  }
                />
              </div>
              <div className="space-y-2">
                <Label>{t("alertSeverity")}</Label>
                <Select
                  value={settings.alertSeverity}
                  onValueChange={(value: SettingsType["alertSeverity"]) =>
                    handleSettingChange("alertSeverity", value)
                  }
                >
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="Low">All Alerts (Low+)</SelectItem>
                    <SelectItem value="Medium">Medium & High Alerts</SelectItem>
                    <SelectItem value="High">
                      Only High-Severity Alerts
                    </SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        {/* System Tab */}
        <TabsContent value="system">
          <Card>
            <CardHeader>
              <CardTitle>{t("systemPreferences")}</CardTitle>
              <CardDescription>{t("systemPreferencesDesc")}</CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="flex items-center justify-between rounded-lg border p-4">
                <div>
                  <h4 className="font-medium">{t("theme")}</h4>
                  <p className="text-sm text-muted-foreground">
                    {t("themeDesc")}
                  </p>
                </div>
                <Select
                  value={settings.theme}
                  onValueChange={(value: SettingsType["theme"]) =>
                    handleSettingChange("theme", value)
                  }
                >
                  <SelectTrigger className="w-[180px]">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="light">Light</SelectItem>
                    <SelectItem value="dark">Dark</SelectItem>
                    <SelectItem value="system">System</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="flex items-center justify-between rounded-lg border p-4">
                <div>
                  <h4 className="font-medium">{t("language")}</h4>
                  <p className="text-sm text-muted-foreground">
                    {t("languageDesc")}
                  </p>
                </div>
                <Select
                  value={settings.language}
                  onValueChange={(value: SettingsType["language"]) =>
                    handleSettingChange("language", value)
                  }
                >
                  <SelectTrigger className="w-[180px]">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="en">English</SelectItem>
                    <SelectItem value="am">Amharic (አማርኛ)</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="flex items-center justify-between rounded-lg border p-4">
                <div>
                  <h4 className="font-medium">{t("autoRefresh")}</h4>
                  <p className="text-sm text-muted-foreground">
                    {t("autoRefreshDesc")}
                  </p>
                </div>
                <Select
                  value={settings.refreshInterval}
                  onValueChange={(value: SettingsType["refreshInterval"]) =>
                    handleSettingChange("refreshInterval", value)
                  }
                >
                  <SelectTrigger className="w-[180px]">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="15s">Every 15 seconds</SelectItem>
                    <SelectItem value="30s">Every 30 seconds</SelectItem>
                    <SelectItem value="60s">Every 1 minute</SelectItem>
                    <SelectItem value="none">Manual</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}

// --- DashboardView ---
function DashboardView() {
  const { t } = useTranslations();
  const { settings } = useContext(SettingsContext);

  // Mock data fetching function
  const refreshData = () => {
    // In a real app, this would be an API call
    console.log("Refreshing dashboard data...");
    toast.info("Dashboard data refreshed!");
  };

  useEffect(() => {
    if (settings.refreshInterval === "none") {
      return;
    }

    const intervalMs =
      parseInt(settings.refreshInterval.replace("s", "")) * 1000;
    const intervalId = setInterval(refreshData, intervalMs);

    return () => clearInterval(intervalId); // Cleanup on component unmount or when interval changes
  }, [settings.refreshInterval]);

  const kpiData = [
    {
      title: t("totalScams"),
      value: "18,432",
      subtitle: "+201 in last 24h",
      icon: ShieldAlert,
      colorClass: "border-red-500",
    },
    {
      title: t("detectionRate"),
      value: "99.7%",
      subtitle: "Industry-leading accuracy",
      icon: Target,
      colorClass: "border-blue-500",
    },
    {
      title: t("activeThreats"),
      value: "14",
      subtitle: "Under investigation",
      icon: Activity,
      colorClass: "border-yellow-500",
    },
    {
      title: t("userReports"),
      value: "256",
      subtitle: "+12 today",
      icon: Flag,
      colorClass: "border-green-500",
    },
  ];

  // FIX: useMemo to prevent re-calculation on every render, which causes the infinite loop
  const trendData = useMemo(
    () =>
      Array.from({ length: 7 }, (_, i) => {
        const d = new Date();
        d.setDate(d.getDate() - (6 - i));
        const phishing = Math.floor(Math.random() * 300) + 100;
        const legitimate = Math.floor(Math.random() * 2000) + 1500;
        return {
          date: d.toISOString().split("T")[0],
          phishing,
          legitimate,
          total: phishing + legitimate,
        };
      }),
    []
  );

  const topScamCategories = [
    { name: "Phishing", value: 65, color: "bg-red-500" },
    { name: "Investment Fraud", value: 15, color: "bg-yellow-500" },
    { name: "Fake Job Ads", value: 10, color: "bg-blue-500" },
    { name: "Lottery Scams", value: 5, color: "bg-purple-500" },
    { name: "Other", value: 5, color: "bg-gray-400" },
  ];

  const liveThreatFeed = [
    {
      id: 1,
      severity: "High",
      description: "Credential theft attempt from evil-domain.com",
      time: "1m ago",
    },
    {
      id: 2,
      severity: "Medium",
      description: "Suspicious link detected in SMS",
      time: "3m ago",
    },
    {
      id: 3,
      severity: "High",
      description: "Bank impersonation scam detected",
      time: "5m ago",
    },
  ];

  const systemStatus = [
    { name: "Detection Engine", status: "Operational", icon: Cpu },
    { name: "API Service", status: "Operational", icon: Server },
    { name: "Database", status: "Operational", icon: Database },
  ];

  return (
    <div className="flex-1 p-6 lg:p-8 space-y-8 overflow-y-auto animate-in fade-in-50 duration-500">
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
        {kpiData.map((item) => (
          <KpiCard key={item.title} {...item} />
        ))}
      </div>
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <Card className="lg:col-span-2">
          <CardHeader>
            <CardTitle>{t("scamAttemptsOverTime")}</CardTitle>
          </CardHeader>
          <CardContent className="pl-2">
            <AnalyticsChart data={trendData} />
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>{t("topScamCategories")}</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            {topScamCategories.map((category) => (
              <div key={category.name}>
                <div className="flex justify-between mb-1">
                  <span className="text-sm font-medium">{category.name}</span>
                  <span className="text-sm text-muted-foreground">
                    {category.value}%
                  </span>
                </div>
                <Progress
                  value={category.value}
                  className="h-2"
                  indicatorClassName={category.color}
                />
              </div>
            ))}
          </CardContent>
        </Card>
      </div>
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <Card className="lg:col-span-2">
          <CardHeader>
            <CardTitle>{t("liveThreatFeed")}</CardTitle>
          </CardHeader>
          <CardContent>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead className="w-[100px]">Severity</TableHead>
                  <TableHead>Description</TableHead>
                  <TableHead className="text-right">Time</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {liveThreatFeed.map((threat) => (
                  <TableRow key={threat.id}>
                    <TableCell>
                      <Badge
                        variant={
                          threat.severity === "High"
                            ? "destructive"
                            : "secondary"
                        }
                      >
                        {threat.severity}
                      </Badge>
                    </TableCell>
                    <TableCell className="font-medium">
                      {threat.description}
                    </TableCell>
                    <TableCell className="text-right text-muted-foreground">
                      {threat.time}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </CardContent>
        </Card>
        <div className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>{t("systemStatus")}</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              {systemStatus.map((service) => (
                <div
                  key={service.name}
                  className="flex items-center justify-between"
                >
                  <div className="flex items-center">
                    <service.icon className="h-4 w-4 mr-2 text-muted-foreground" />
                    <span className="text-sm font-medium">{service.name}</span>
                  </div>
                  <div className="flex items-center">
                    <div className="h-2 w-2 rounded-full bg-green-500 mr-2"></div>
                    <span className="text-sm text-muted-foreground">
                      {service.status}
                    </span>
                  </div>
                </div>
              ))}
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>{t("scamOfTheDay")}</CardTitle>
            </CardHeader>
            <CardContent>
              <h4 className="font-semibold">
                "Netflix Subscription Expired" Phishing
              </h4>
              <p className="text-sm text-muted-foreground mt-2">
                A widespread email campaign is tricking users into entering
                payment details on a fake Netflix login page.
              </p>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}

// --- DIALOG COMPONENTS ---
function ScanUrlDialog({
  open,
  onOpenChange,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}) {
  const [url, setUrl] = useState("");
  const [isScanning, setIsScanning] = useState(false);
  const [result, setResult] = useState<{
    isMalicious: boolean;
    message: string;
  } | null>(null);

  const handleScan = async () => {
    if (!url) return;
    setIsScanning(true);
    setResult(null);
    await new Promise((resolve) => setTimeout(resolve, 1500));
    const knownMaliciousDomains = [
      "evil-domain.com",
      "malicious-site.net",
      "phishing-central.org",
    ];
    const isMalicious = knownMaliciousDomains.some((domain) =>
      url.includes(domain)
    );
    setResult({
      isMalicious,
      message: isMalicious
        ? "This URL is flagged as malicious by our database."
        : "This URL appears to be safe.",
    });
    setIsScanning(false);
  };

  useEffect(() => {
    if (!open) {
      setTimeout(() => {
        setUrl("");
        setIsScanning(false);
        setResult(null);
      }, 200);
    }
  }, [open]);

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>Scan URL</DialogTitle>
          <DialogDescription>
            Enter a URL to check for threats. Try a known malicious domain like
            "evil-domain.com" to see a positive detection.
          </DialogDescription>
        </DialogHeader>
        <div className="grid gap-4 py-4">
          <div className="grid grid-cols-4 items-center gap-4">
            <Label htmlFor="url" className="text-right">
              URL
            </Label>
            <Input
              id="url"
              value={url}
              onChange={(e) => setUrl(e.target.value)}
              className="col-span-3"
              placeholder="https://example.com"
            />
          </div>
          {result && (
            <div
              className={`p-3 rounded-md text-sm ${
                result.isMalicious
                  ? "bg-red-100 text-red-800"
                  : "bg-green-100 text-green-800"
              }`}
            >
              {result.message}
            </div>
          )}
        </div>
        <DialogFooter>
          <Button onClick={handleScan} disabled={isScanning || !url}>
            {isScanning ? (
              <>
                <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-primary-foreground mr-2"></div>
                Scanning...
              </>
            ) : (
              <>
                <ScanLine className="h-4 w-4 mr-2" />
                Scan
              </>
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

function ReportScamDialog({
  open,
  onOpenChange,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}) {
  const [source, setSource] = useState("");
  const [description, setDescription] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);

  const handleSubmit = async () => {
    if (!source || !description) {
      toast.error("Please fill out all fields to submit a report.");
      return;
    }
    setIsSubmitting(true);
    await new Promise((resolve) => setTimeout(resolve, 1500));
    setIsSubmitting(false);
    toast.success("Scam report submitted successfully!", {
      description: "Thank you for helping keep the community safe.",
    });
    onOpenChange(false);
  };

  useEffect(() => {
    if (!open) {
      setTimeout(() => {
        setSource("");
        setDescription("");
        setIsSubmitting(false);
      }, 200);
    }
  }, [open]);

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>Report a Scam</DialogTitle>
          <DialogDescription>
            Help the community by reporting a suspicious URL, email, or message.
          </DialogDescription>
        </DialogHeader>
        <div className="grid gap-4 py-4">
          <div className="space-y-2">
            <Label htmlFor="source">Scam Source (URL, Email, etc.)</Label>
            <Input
              id="source"
              value={source}
              onChange={(e) => setSource(e.target.value)}
              placeholder="e.g., suspicious-link.com"
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="description">Description</Label>
            <Textarea
              id="description"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="Describe the scam, including any suspicious details."
            />
          </div>
        </div>
        <DialogFooter>
          <Button
            onClick={handleSubmit}
            disabled={isSubmitting || !source || !description}
          >
            {isSubmitting ? (
              <>
                <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-primary-foreground mr-2"></div>
                Submitting...
              </>
            ) : (
              <>
                <Flag className="h-4 w-4 mr-2" />
                Submit Report
              </>
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// --- MAIN DASHBOARD WRAPPER ---
function DashboardContent({ onLogout }: { onLogout: () => void }) {
  const { t } = useTranslations();
  // FIX: Use a language-independent key for the active view
  const [activeView, setActiveView] = useState("dashboard");
  const [isScanUrlOpen, setIsScanUrlOpen] = useState(false);
  const [isReportScamOpen, setIsReportScamOpen] = useState(false);

  const renderActiveView = () => {
    switch (activeView) {
      case "dashboard":
        return <DashboardView />;
      case "reports":
        return <ReportsView />;
      case "userManagement":
        return <UserManagementView />;
      case "threatMap":
        return <ThreatMapView />;
      case "settings":
        return <SettingsView />;
      default:
        return <DashboardView />;
    }
  };

  return (
    <div className="min-h-screen flex bg-background font-sans">
      <Sidebar
        activeView={activeView}
        setActiveView={setActiveView}
        onLogout={onLogout}
      />
      <main className="flex-1 flex flex-col">
        <header className="bg-card/80 backdrop-blur-sm border-b border-border sticky top-0 z-30">
          <div className="px-6 h-16 flex items-center justify-between">
            <h1 className="text-xl font-semibold text-foreground">
              {t(activeView as keyof typeof translations.en)}
            </h1>
            {activeView === "dashboard" && (
              <div className="flex items-center space-x-2">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => setIsScanUrlOpen(true)}
                >
                  <ScanLine className="h-4 w-4 mr-2" />
                  {t("scanUrl")}
                </Button>
                <Button size="sm" onClick={() => setIsReportScamOpen(true)}>
                  <Flag className="h-4 w-4 mr-2" />
                  {t("reportScam")}
                </Button>
              </div>
            )}
          </div>
        </header>

        {renderActiveView()}
      </main>
      <Toaster richColors position="top-right" />
      <ScanUrlDialog open={isScanUrlOpen} onOpenChange={setIsScanUrlOpen} />
      <ReportScamDialog
        open={isReportScamOpen}
        onOpenChange={setIsReportScamOpen}
      />
    </div>
  );
}

// --- MAIN PAGE COMPONENT WITH AUTHENTICATION ---
export default function AdminPage() {
  const [isAuthenticated, setIsAuthenticated] = useState(false);

  const handleLogin = () => {
    setIsAuthenticated(true);
  };

  const handleLogout = () => {
    setIsAuthenticated(false);
  };

  if (!isAuthenticated) {
    return <LoginPage onLoginSuccess={handleLogin} />;
  }

  return (
    <SettingsProvider>
      <DashboardContent onLogout={handleLogout} />
    </SettingsProvider>
  );
}
